# Generated by Django 5.2.7 on 2025-10-20 04:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_url', models.TextField()),
                ('annotated_url', models.TextField(blank=True, null=True)),
                ('model_version', models.CharField(default='1.0', max_length=20)),
                ('pod_id', models.CharField(blank=True, default='', max_length=64)),
                ('total_objects', models.IntegerField(default=0)),
                ('avg_conf', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('klass', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='detections.detection')),
            ],
        ),
    ]
